services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - "../public:/var/www/project/public"
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php82-service

  caddy:
    image: caddy
    container_name: caddy
    ports:
      - "8088:80"
    volumes:
      - "../public:/var/www/project/public"
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - php82-service

  php82-service:
    container_name: php82-service
    build:
      context: ..
      dockerfile: infra/php/Dockerfile
    volumes:
      - "../:/var/www/project"
    depends_on:
      - postgres

  postgres:
    container_name: "postgres"
    image: postgres:16
    ports:
      - 6543:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db
