<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0lKb7Qa\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0lKb7Qa/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container0lKb7Qa.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container0lKb7Qa\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container0lKb7Qa\App_KernelDevDebugContainer([
    'container.build_hash' => '0lKb7Qa',
    'container.build_id' => 'bf343d83',
    'container.build_time' => 1729120102,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container0lKb7Qa');
