<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'api_login' => [[], ['_controller' => 'App\\Controller\\ApiLoginController::index'], [], [['text', '/api/login']], [], [], []],
    'api_test' => [[], ['_controller' => 'App\\Controller\\ApiLoginController::test'], [], [['text', '/api/test']], [], [], []],
    'lucky' => [[], ['_controller' => 'App\\Controller\\LuckyController::lucky'], [], [['text', '/lucky']], [], [], []],
    'test' => [[], ['_controller' => 'App\\Controller\\LuckyController::test'], [], [['text', '/test']], [], [], []],
    'custom_event' => [[], ['_controller' => 'App\\Controller\\LuckyController::customEvent'], [], [['text', '/custom_event']], [], [], []],
    'app_register' => [[], ['_controller' => 'App\\Controller\\RegistrationController::register'], [], [['text', '/']], [], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/login']], [], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], [], []],
    'App\Controller\ApiLoginController::index' => [[], ['_controller' => 'App\\Controller\\ApiLoginController::index'], [], [['text', '/api/login']], [], [], []],
    'App\Controller\ApiLoginController::test' => [[], ['_controller' => 'App\\Controller\\ApiLoginController::test'], [], [['text', '/api/test']], [], [], []],
    'App\Controller\LuckyController::lucky' => [[], ['_controller' => 'App\\Controller\\LuckyController::lucky'], [], [['text', '/lucky']], [], [], []],
    'App\Controller\LuckyController::test' => [[], ['_controller' => 'App\\Controller\\LuckyController::test'], [], [['text', '/test']], [], [], []],
    'App\Controller\LuckyController::customEvent' => [[], ['_controller' => 'App\\Controller\\LuckyController::customEvent'], [], [['text', '/custom_event']], [], [], []],
    'App\Controller\RegistrationController::register' => [[], ['_controller' => 'App\\Controller\\RegistrationController::register'], [], [['text', '/']], [], [], []],
    'App\Controller\SecurityController::login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/login']], [], [], []],
    'App\Controller\SecurityController::logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], [], []],
];
